spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/smart?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: wangqi
